### PR TITLE
functionality refactored and is clean now (JSX needs refactoring yet)

### PR DESCRIPTION
**Pull request by Sky-De**
### what I've done
1. I debugged the issue that I mentioned on the page of issue #3 
1. I implemented custom hook for handling  fetching functionality ( useExchange.js )
2. I created _changeHandler_ function to handle states onChange dynamically
3. I used _useExchange_ hook in CurrencyForm.js to handle fetching data and sharing different phases of request

### What you need to do in the next step
- refactor JSX for better readability and maintainability
- create an error alert and use the isError state to render it in the UI

### CODE REVIEW

**Comment by Sky-De** [comment]
@cjstyles6 hi there, did you take a look this PR?

**Comment by Sky-De** [comment]
@cjstyles6 Hi again, it has been a while since I created this PR, why you don't check it?

**Comment by Sky-De** [comment]
@cjstyles6

**Comment by cjstyles6** [comment]
So sorry bro, I've been so busy with school work😔.. I'll check it tomorrow. Thanks for the assist I appreciate

**Comment by Sky-De** [comment]
@cjstyles6 is it tommorow yet? shall i close this PR ? let me know about it, thanks

**Pull request merged**
